ALTER TABLE public.games
ADD COLUMN IF NOT EXISTS deck JSONB,
ADD COLUMN IF NOT EXISTS discard_pile JSONB,
ADD COLUMN IF NOT EXISTS top_card JSONB,
ADD COLUMN IF NOT EXISTS current_color TEXT,
ADD COLUMN IF NOT EXISTS direction TEXT DEFAULT 'clockwise',
ADD COLUMN IF NOT EXISTS player_order UUID[] DEFAULT ARRAY[]::UUID[],
ADD COLUMN IF NOT EXISTS active_player_index INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS draw_penalty INTEGER DEFAULT 0;

ALTER TABLE public.game_players
ADD COLUMN IF NOT EXISTS hand_cards JSONB DEFAULT '[]'::jsonb;
